In [2]:
!pip install pandas

Collecting pandas
  Downloading pandas-2.3.3-cp311-cp311-macosx_10_9_x86_64.whl.metadata (91 kB)
Requirement already satisfied: numpy>=1.23.2 in /Users/yyankovskyygmail.com/opt/anaconda3/envs/py311/lib/python3.11/site-packages (from pandas) (2.3.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/yyankovskyygmail.com/opt/anaconda3/envs/py311/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Collecting pytz>=2020.1 (from pandas)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Requirement already satisfied: tzdata>=2022.7 in /Users/yyankovskyygmail.com/opt/anaconda3/envs/py311/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/yyankovskyygmail.com/opt/anaconda3/envs/py311/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-2.3.3-cp311-cp311-macosx_10_9_x86_64.whl (11.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 14.2 MB/s  0:00:0014.2 MB/s eta 0:00:01
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Installing collected packages: pytz, pandas
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [pandas]━━━━ 1/2 [pandas]
Successfully installed pandas-2.3.3 pytz-2025.2

In [4]:
import pandas as pd

# Sample data
data = {
    'product_category': ['A', 'A', 'A', 'B', 'B', 'B', 'C', 'C', 'C'],
    'product_id': ['101', '102', '103', '201', '202', '203', '301', '302', '303'],
    'sales': [100, 200, 150, 300, 250, 200, 400, 500, 300]
}
df = pd.DataFrame(data)
df.head(3)

  product_category product_id  sales
0                A        101    100
1                A        102    200
2                A        103    150

In [9]:
# Calculate total sales per product within each category
df_grouped = df.groupby(['product_category', 'product_id']).agg(total_sales=('sales', 'sum')).reset_index()
df_grouped.head(3)

  product_category product_id  total_sales
0                A        101          100
1                A        102          200
2                A        103          150

In [8]:
df_grouped = df.groupby(['product_category', 'product_id'])['sales'].agg('sum').reset_index()
df.group
df_grouped.head(3)

  product_category product_id  sales
0                A        101    100
1                A        102    200
2                A        103    150

In [10]:
# Calculate total sales per category
category_totals = df.groupby('product_category')['sales'].sum().rename('category_total_sales')
category_totals.head(3)

product_category
A     450
B     750
C    1200
Name: category_total_sales, dtype: int64

In [11]:
category_totals = df.groupby('product_category').agg(category_total_sales=('sales', 'sum')).reset_index()
category_totals.head(3)

  product_category  category_total_sales
0                A                   450
1                B                   750
2                C                  1200

In [ ]:
# Merge total sales per product with total sales per category
df_merged = pd.merge(df_grouped, category_totals, on='product_category')

# Calculate the sales percentage of each product within its category
df_merged['sales_percentage'] = (df_merged['total_sales'] / df_merged['category_total_sales']) * 100

# Display the result
print(df_merged[['product_category', 'product_id', 'sales_percentage']])

In [ ]:
# How would you calculate the monthly sales trends for each product using pandas?

In [12]:
data = {
    'transaction_date': ['2022-01-15', '2023-01-20', '2022-02-15', '2023-02-20', '2022-03-15', '2023-04-01'],
    'product_id': ['101', '101', '102', '102', '101', '102'],
    'sales': [100, 150, 200, 250, 300, 350]
}
df = pd.DataFrame(data)

In [18]:
df['month'] = pd.to_datetime(df['transaction_date']).dt.to_period('M')
monthly_sales = df.groupby(['product_id', 'month'])['sales'].sum().unstack().fillna(0)
monthly_sales.head(2)

month       2022-01  2022-02  2022-03  2023-01  2023-02  2023-04
product_id
101           100.0      0.0    300.0    150.0      0.0      0.0
102             0.0    200.0      0.0      0.0    250.0    350.0

In [20]:
print(monthly_sales[['2022-01']])

month       2022-01
product_id
101           100.0
102             0.0